### ISSUE TITLE
[FEATURE] Monitor SMART data of the disk drives in the Harvester nodes

### ISSUE THREAD

**Issue by votdev** [yasker/vm#7416]
**Is your feature request related to a problem? Please describe.**
It would be nice to give the user the possibility to monitor the disks (HDD/SSD/NVMe/...) in the Harvester nodes using SMART.

**Describe the solution you'd like**
Whether the data is provided via a Prometheus exporter or in some other way still needs to be evaluated and discussed.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nnewc** [comment]
For NVMe drives I have this as a part of my harvester config:

```yaml
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: nvme-exporter
        namespace: cattle-monitoring-system
      spec:
        selector:
          matchLabels:
            app: nvme-exporter
        template:
          metadata:
            labels:
              app: nvme-exporter
          spec:
            tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            containers:
            - name: nvme-exporter
              image: "fritchie/nvme_exporter"
              command: ["nvme_exporter"]
              # nvme-cli requires pod to be privileged
              securityContext:
                privileged: true
              ports:
              - containerPort: 9998
                protocol: TCP
      ---
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: nvme-exporter
        namespace: cattle-monitoring-system
        labels:
          app: nvme-exporter
      spec:
        selector:
          matchLabels:
            app: nvme-exporter
        endpoints:
        - port: metrics
          path: /metrics
```
